/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module full_adder(a, b, Cin, sum, Cout);
  wire _0_;
  wire C1;
  wire C2;
  input Cin;
  output Cout;
  wire S1;
  input a;
  input b;
  output sum;
  assign _0_ = C1 | C2;
  half_adder HA1 (
    .Carry(C1),
    .a(a),
    .b(b),
    .sum(S1)
  );
  half_adder HA2 (
    .Carry(C2),
    .a(Cin),
    .b(S1),
    .sum(sum)
  );
  assign Cout = _0_;
endmodule

module half_adder(a, b, sum, Carry);
  wire _0_;
  wire _1_;
  output Carry;
  input a;
  input b;
  output sum;
  assign _0_ = a & b;
  assign _1_ = a ^ b;
  assign sum = _1_;
  assign Carry = _0_;
endmodule
