/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module full_adder(a, b, Cin, sum, Cout);
  wire C1;
  wire C2;
  input Cin;
  output Cout;
  wire S1;
  input a;
  input b;
  output sum;
  sky130_fd_sc_ls__or2_1 _0_ (
    .A(C2),
    .B(C1),
    .X(Cout)
  );
  half_adder HA1 (
    .Carry(C1),
    .a(a),
    .b(b),
    .sum(S1)
  );
  half_adder HA2 (
    .Carry(C2),
    .a(Cin),
    .b(S1),
    .sum(sum)
  );
endmodule

module half_adder(a, b, sum, Carry);
  output Carry;
  input a;
  input b;
  output sum;
  sky130_fd_sc_ls__and2_1 _0_ (
    .A(b),
    .B(a),
    .X(Carry)
  );
  sky130_fd_sc_ls__xor2_1 _1_ (
    .A(b),
    .B(a),
    .X(sum)
  );
endmodule
